version: '3.8'
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
  server:
    build: ./server
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - JWT_SECRET=dev-manish-9599
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo_data:
