name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: Build server
      run: |
        cd server
        go build ./...
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Build client
      run: |
        cd client
        npm install
        npm run build --if-present
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    - name: Docker Compose build
      run: docker-compose build
